/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fujita' at '14/10/20 15:17' with Gradle 2.1
 *
 * @author fujita, @date 14/10/20 15:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
